/*
 * generated by Xtext 2.25.0
 */
package re.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import re.FactorRuntimeModule;
import re.FactorStandaloneSetup;
import re.ide.FactorIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class FactorWebSetup extends FactorStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FactorRuntimeModule(), new FactorIdeModule(), new FactorWebModule()));
	}
	
}
