/*
 * generated by Xtext 2.25.0
 */
package re.factor.validation;

import org.eclipse.xtext.validation.Check;

import re.factor.model.ModelPackage;
//import re.factor.model.Refactor;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class ModelValidator extends AbstractModelValidator {

	
	public static final String INVALID_NAME = "invalidName";
////
//	@Check
//	public void checkGreetingStartsWithCapital(Refactor refactor) {
//		if (!Character.isUpperCase(refactor.getModifications().toString().charAt(0))) {
//			warning("Name should start with a capital",
//					null,
//					INVALID_NAME);
//		}
//	}
	
}
