/*
 * generated by Xtext 2.25.0
 */
package re.factor.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class ModelWebModule extends AbstractModelWebModule {
}
