/*
 * generated by Xtext 2.25.0
 */
package re.factor.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import re.factor.ModelRuntimeModule;
import re.factor.ModelStandaloneSetup;
import re.factor.ide.ModelIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class ModelWebSetup extends ModelStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ModelRuntimeModule(), new ModelIdeModule(), new ModelWebModule()));
	}
	
}
