/*
 * generated by Xtext 2.25.0
 */
package re;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FactorStandaloneSetup extends FactorStandaloneSetupGenerated {

	public static void doSetup() {
		new FactorStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
