/*
 * generated by Xtext 2.25.0
 */
package re.factor.ui.labeling;

import com.google.inject.Inject;

import re.factor.model.Refactor;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class ModelLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public ModelLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	// Labels and icons can be computed like this:
	
	String text(Refactor ele) {
		return "A greeting to " + ele.toString();
	}

	String image(Refactor ele) {
		return "Greeting.gif";
	}
}

