/*
 * generated by Xtext 2.25.0
 */
package re.factor;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ModelStandaloneSetup extends ModelStandaloneSetupGenerated {

	public static void doSetup() {
		new ModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
