/*
 * generated by Xtext 2.25.0
 */
package re.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FactorUiModule extends AbstractFactorUiModule {

	public FactorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
