/*
 * generated by Xtext 2.25.0
 */
package re.factor.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import re.factor.ModelRuntimeModule;
import re.factor.ModelStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ModelIdeSetup extends ModelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ModelRuntimeModule(), new ModelIdeModule()));
	}
	
}
