/*
 * generated by Xtext 2.25.0
 */
package re.factor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ModelUiModule extends AbstractModelUiModule {

	public ModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
