/*
 * generated by Xtext 2.25.0
 */
package re.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import re.FactorRuntimeModule;
import re.FactorStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FactorIdeSetup extends FactorStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FactorRuntimeModule(), new FactorIdeModule()));
	}
	
}
