/*
 * generated by Xtext 2.25.0
 */
package re.validation;

import org.eclipse.xtext.validation.Check;

import re.factor.FactorPackage;
import re.factor.Greeting;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class FactorValidator extends AbstractFactorValidator {

	
	public static final String INVALID_NAME = "invalidName";

	@Check
	public void checkGreetingStartsWithCapital(Greeting greeting) {
		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
			warning("Name should start with a capital",
					FactorPackage.Literals.GREETING__NAME,
					INVALID_NAME);
		}
	}
	
}
